### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by Prince527GitHub** [Wam25/SpaceWarp#5]
Also if you just want to download the document: [README.md](https://github.com/Wam25/SpaceWarp/files/11748978/README.md)

I believe the readme is kinda lame so ive improved it

# SpaceWarp

Welcome to SpaceWarp, currently a game that barely works.

**Play the game [here](https://wam25.github.io/SpaceWarp/)** or download it from the latest workflow [here](https://github.com/Wam25/SpaceWarp/actions) (Note: currently not compatible with Mac).

## How to Play

**Controls:**
- Use the left and right arrow keys to move your character.
- Press the spacebar or up arrow key to jump.
- Navigate menus by using the up and down arrow keys.
- Select an item in the menu by pressing the enter key.
- Press 'r' to restart the game.

**Objective:**
Your mission is to reach the spaceship (or whatever that is) and emerge victorious. But beware, the path is filled with challenges!

**Gameplay Tips:**
- Press and hold a button to activate it. This action will open the door(s) with the same color for 5 seconds.
- Collect keys to permanently open all doors of the corresponding color.

**Comment by LMacrini** [comment]
i made the readme in like 2 seconds, ill add this for sure
